name: "Upload logs"
description: "Upload logs from the test run"
runs:
  using: composite
  steps:
    - run: |
        LOGS=test-logs
        if [[ $RUNNER_OS == Windows ]]; then
          mkdir -p "$LOGS"
        else
          rsync -ma --include='*/' --include='*.tap' --include='*.log' --include='Test*.webm' --exclude='*' . "$LOGS"
        fi
        for file in \
          {"${XDG_CACHE_HOME:-$HOME/.cache}/telepresence/logs","$HOME/Library/Logs/telepresence","$LOCALAPPDATA/telepresence/logs","."}/*.log
        do
          if [ -s "$file" ]; then
            cp -v "$file" "$LOGS"
          fi
        done
      shell: bash
      name: Gather logs
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: test-logs
        path: |
          test-logs/*
